POST http://localhost:8080/api/vehiculos
Content-Type: application/json

{
  "placa": "CER-186",
  "marca": "AUTECO",
  "modelo": "2026",
  "celda": {
    "numeroCelda": 1
  },
  "usuario": {
    "cedula": "1001"
  }
}